#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2018.2 (64-bit)
#
# Filename    : system.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Tue Sep 17 13:21:59 WEST 2019
# SW Build 2258646 on Thu Jun 14 20:02:38 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved. 
#
# usage: system.sh [-help]
# usage: system.sh [-lib_map_path]
# usage: system.sh [-noclean_files]
# usage: system.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'system.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xil_defaultlib xpm microblaze_v10_0_7 lmb_v10_v3_0_9 lmb_bram_if_cntlr_v4_0_15 blk_mem_gen_v8_4_1 axi_lite_ipif_v3_0_4 mdm_v3_2_14 lib_cdc_v1_0_2 proc_sys_reset_v5_0_12 lib_bmg_v1_0_10 fifo_generator_v13_2_2 lib_fifo_v1_0_11 axi_ethernetlite_v3_0_15 lib_pkg_v1_0_2 interrupt_control_v3_1_4 axi_iic_v2_0_20 lib_srl_fifo_v1_0_2 axi_uartlite_v2_0_21 axi_timer_v2_0_19 axi_gpio_v2_0_19 dist_mem_gen_v8_0_12 axi_quad_spi_v3_2_16 axi_intc_v4_1_11 xlconcat_v2_1_1 emc_common_v3_0_5 axi_emc_v3_0_17 xlconstant_v1_1_5 smartconnect_v1_0 generic_baseblocks_v2_1_0 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_17 axi_data_fifo_v2_1_16 axi_crossbar_v2_1_18 axi_protocol_converter_v2_1_17)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "system.sh - Script generated by export_simulation (Vivado v2018.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/adb9" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/adb9" +incdir+"/home/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "/home/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "/home/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "/home/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "/home/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "/home/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "/home/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "/home/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "/home/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "/home/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/adb9" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/adb9" +incdir+"/home/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "/home/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "/home/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "/home/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "/home/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work microblaze_v10_0_7 $vhdlan_opts \
    "$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/b649/hdl/microblaze_v10_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_sys_mb_0/sim/system_sys_mb_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lmb_v10_v3_0_9 $vhdlan_opts \
    "$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/78eb/hdl/lmb_v10_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_sys_dlmb_0/sim/system_sys_dlmb_0.vhd" \
    "$ref_dir/../../../bd/system/ip/system_sys_ilmb_0/sim/system_sys_ilmb_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lmb_bram_if_cntlr_v4_0_15 $vhdlan_opts \
    "$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/92fd/hdl/lmb_bram_if_cntlr_v4_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_sys_dlmb_cntlr_0/sim/system_sys_dlmb_cntlr_0.vhd" \
    "$ref_dir/../../../bd/system/ip/system_sys_ilmb_cntlr_0/sim/system_sys_ilmb_cntlr_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_4_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/adb9" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/adb9" +incdir+"/home/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/67d8/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/adb9" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/adb9" +incdir+"/home/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_sys_lmb_bram_0/sim/system_sys_lmb_bram_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/cced/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mdm_v3_2_14 $vhdlan_opts \
    "$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/5125/hdl/mdm_v3_2_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_sys_mb_debug_0/sim/system_sys_mb_debug_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_12 $vhdlan_opts \
    "$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/f86a/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_sys_rstgen_0/sim/system_sys_rstgen_0.vhd" \
    "$ref_dir/../../../bd/system/ip/system_sys_200m_rstgen_0/sim/system_sys_200m_rstgen_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/adb9" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/adb9" +incdir+"/home/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/phy/mig_7series_v4_1_ddr_byte_group_io.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/phy/mig_7series_v4_1_ddr_mc_phy.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_ocd_edge.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/phy/mig_7series_v4_1_ddr_mc_phy_wrapper.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_ocd_po_cntlr.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_ocd_data.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_dqs_found_cal_hr.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/phy/mig_7series_v4_1_poc_tap_base.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/phy/mig_7series_v4_1_poc_pd.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_ocd_lim.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_dqs_found_cal.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/phy/mig_7series_v4_1_poc_meta.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_wrlvl_off_delay.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_wrlvl.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/phy/mig_7series_v4_1_poc_cc.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_top.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_oclkdelay_cal.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/phy/mig_7series_v4_1_ddr_if_post_fifo.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/phy/mig_7series_v4_1_poc_edge_store.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_ck_addr_cmd_delay.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_init.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_wrcal.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_ocd_samp.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/phy/mig_7series_v4_1_ddr_byte_lane.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/phy/mig_7series_v4_1_ddr_of_pre_fifo.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/phy/mig_7series_v4_1_ddr_prbs_gen.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/phy/mig_7series_v4_1_ddr_calib_top.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_ocd_mux.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_ocd_cntlr.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_4lanes.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_prbs_rdlvl.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/phy/mig_7series_v4_1_poc_top.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_rdlvl.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_tempmon.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/phy/mig_7series_v4_1_ddr_skip_calib_tap.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/axi/mig_7series_v4_1_axi_mc_r_channel.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/axi/mig_7series_v4_1_axi_mc_cmd_arbiter.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/axi/mig_7series_v4_1_axi_mc_b_channel.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/axi/mig_7series_v4_1_axi_mc_aw_channel.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/axi/mig_7series_v4_1_ddr_command_fifo.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/axi/mig_7series_v4_1_axi_mc_wr_cmd_fsm.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/axi/mig_7series_v4_1_axi_mc_incr_cmd.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/axi/mig_7series_v4_1_axi_mc_wrap_cmd.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/axi/mig_7series_v4_1_ddr_carry_latch_or.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/axi/mig_7series_v4_1_ddr_axi_upsizer.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/axi/mig_7series_v4_1_axi_mc_simple_fifo.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/axi/mig_7series_v4_1_axi_mc_ar_channel.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/axi/mig_7series_v4_1_ddr_carry_and.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/axi/mig_7series_v4_1_axi_ctrl_addr_decode.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/axi/mig_7series_v4_1_ddr_axi_register_slice.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/axi/mig_7series_v4_1_ddr_a_upsizer.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/axi/mig_7series_v4_1_axi_ctrl_top.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/axi/mig_7series_v4_1_axi_mc_cmd_fsm.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/axi/mig_7series_v4_1_ddr_comparator.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/axi/mig_7series_v4_1_axi_ctrl_reg_bank.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/axi/mig_7series_v4_1_ddr_axic_register_slice.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/axi/mig_7series_v4_1_axi_mc_fifo.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/axi/mig_7series_v4_1_ddr_carry_or.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/axi/mig_7series_v4_1_axi_ctrl_read.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/axi/mig_7series_v4_1_axi_mc.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/axi/mig_7series_v4_1_ddr_r_upsizer.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/axi/mig_7series_v4_1_axi_ctrl_reg.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/axi/mig_7series_v4_1_ddr_carry_latch_and.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/axi/mig_7series_v4_1_ddr_w_upsizer.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/axi/mig_7series_v4_1_axi_ctrl_write.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/axi/mig_7series_v4_1_ddr_comparator_sel_static.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/axi/mig_7series_v4_1_axi_mc_cmd_translator.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/axi/mig_7series_v4_1_axi_mc_w_channel.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/axi/mig_7series_v4_1_ddr_comparator_sel.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/controller/mig_7series_v4_1_rank_mach.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/controller/mig_7series_v4_1_bank_common.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/controller/mig_7series_v4_1_round_robin_arb.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/controller/mig_7series_v4_1_bank_compare.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/controller/mig_7series_v4_1_bank_queue.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/controller/mig_7series_v4_1_arb_select.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/controller/mig_7series_v4_1_rank_common.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/controller/mig_7series_v4_1_rank_cntrl.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/controller/mig_7series_v4_1_col_mach.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/controller/mig_7series_v4_1_bank_state.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/controller/mig_7series_v4_1_bank_mach.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/controller/mig_7series_v4_1_arb_row_col.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/controller/mig_7series_v4_1_arb_mux.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/controller/mig_7series_v4_1_bank_cntrl.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/controller/mig_7series_v4_1_mc.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/ip_top/mig_7series_v4_1_memc_ui_top_axi.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/ip_top/mig_7series_v4_1_mem_intfc.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/ecc/mig_7series_v4_1_fi_xor.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/ecc/mig_7series_v4_1_ecc_gen.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/ecc/mig_7series_v4_1_ecc_dec_fix.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/ecc/mig_7series_v4_1_ecc_buf.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/ecc/mig_7series_v4_1_ecc_merge_enc.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/ui/mig_7series_v4_1_ui_rd_data.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/ui/mig_7series_v4_1_ui_cmd.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/ui/mig_7series_v4_1_ui_top.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/ui/mig_7series_v4_1_ui_wr_data.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/clocking/mig_7series_v4_1_clk_ibuf.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/clocking/mig_7series_v4_1_tempmon.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/clocking/mig_7series_v4_1_iodelay_ctrl.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/clocking/mig_7series_v4_1_infrastructure.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/system_axi_ddr_cntrl_0_mig_sim.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/rtl/system_axi_ddr_cntrl_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_bmg_v1_0_10 $vhdlan_opts \
    "$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/9340/hdl/lib_bmg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/adb9" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/adb9" +incdir+"/home/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/7aff/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_2 $vhdlan_opts \
    "$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/7aff/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/adb9" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/adb9" +incdir+"/home/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/7aff/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_fifo_v1_0_11 $vhdlan_opts \
    "$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/6078/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_ethernetlite_v3_0_15 $vhdlan_opts \
    "$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/127d/hdl/axi_ethernetlite_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_ethernet_0/sim/system_axi_ethernet_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/8e66/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_iic_v2_0_20 $vhdlan_opts \
    "$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/df5e/hdl/axi_iic_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_iic_main_0/sim/system_axi_iic_main_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_uartlite_v2_0_21 $vhdlan_opts \
    "$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/a15e/hdl/axi_uartlite_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_uart_0/sim/system_axi_uart_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_timer_v2_0_19 $vhdlan_opts \
    "$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/0a2c/hdl/axi_timer_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_timer_0/sim/system_axi_timer_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_gpio_v2_0_19 $vhdlan_opts \
    "$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/c193/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_gpio_lcd_0/sim/system_axi_gpio_lcd_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work dist_mem_gen_v8_0_12 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/adb9" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/adb9" +incdir+"/home/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/d46a/simulation/dist_mem_gen_v8_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_quad_spi_v3_2_16 $vhdlan_opts \
    "$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/92ac/hdl/axi_quad_spi_v3_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_spi_0/sim/system_axi_spi_0.vhd" \
    "$ref_dir/../../../bd/system/ip/system_axi_gpio_0/sim/system_axi_gpio_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_intc_v4_1_11 $vhdlan_opts \
    "$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/2fec/hdl/axi_intc_v4_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_intc_0/sim/system_axi_intc_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconcat_v2_1_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/adb9" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/adb9" +incdir+"/home/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/2f66/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/adb9" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/adb9" +incdir+"/home/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_sys_concat_intc_0/sim/system_sys_concat_intc_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work emc_common_v3_0_5 $vhdlan_opts \
    "$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/d806/hdl/emc_common_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_emc_v3_0_17 $vhdlan_opts \
    "$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/1d19/hdl/axi_emc_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_linear_flash_0/sim/system_axi_linear_flash_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/adb9" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/adb9" +incdir+"/home/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ipshared/6e8a/axi_sysid.v" \
    "$ref_dir/../../../bd/system/ipshared/common/up_axi.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_sysid_0_0/sim/system_axi_sysid_0_0.v" \
    "$ref_dir/../../../bd/system/ipshared/a6f2/sysid_rom.v" \
    "$ref_dir/../../../bd/system/ip/system_rom_sys_0_0/sim/system_rom_sys_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/adb9" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/adb9" +incdir+"/home/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/f1c3/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/adb9" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/adb9" +incdir+"/home/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_GND_1_0/sim/system_GND_1_0.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_mem_interconnect_0/bd_0/sim/bd_518a.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/adb9" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/adb9" +incdir+"/home/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/5bb9/hdl/sc_util_v1_0_vl_rfs.sv" \
    "$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/5160/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/adb9" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/adb9" +incdir+"/home/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_12/sim/bd_518a_s00a2s_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_21/sim/bd_518a_s01a2s_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_27/sim/bd_518a_s02a2s_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_36/sim/bd_518a_s03a2s_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_43/sim/bd_518a_s04a2s_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/adb9" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/adb9" +incdir+"/home/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/acc2/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/adb9" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/adb9" +incdir+"/home/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_47/sim/bd_518a_m00s2a_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/adb9" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/adb9" +incdir+"/home/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/28cb/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/adb9" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/adb9" +incdir+"/home/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_53/sim/bd_518a_m00e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/adb9" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/adb9" +incdir+"/home/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/f90c/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/adb9" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/adb9" +incdir+"/home/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_48/sim/bd_518a_m00arn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_49/sim/bd_518a_m00rn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_50/sim/bd_518a_m00awn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_51/sim/bd_518a_m00wn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_52/sim/bd_518a_m00bn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_44/sim/bd_518a_sawn_3.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_45/sim/bd_518a_swn_3.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_46/sim/bd_518a_sbn_3.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/adb9" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/adb9" +incdir+"/home/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/afa8/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/adb9" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/adb9" +incdir+"/home/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_40/sim/bd_518a_s04mmu_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/adb9" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/adb9" +incdir+"/home/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/4521/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/adb9" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/adb9" +incdir+"/home/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_41/sim/bd_518a_s04tr_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/adb9" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/adb9" +incdir+"/home/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/d1fc/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/adb9" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/adb9" +incdir+"/home/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_42/sim/bd_518a_s04sic_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_37/sim/bd_518a_sawn_2.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_38/sim/bd_518a_swn_2.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_39/sim/bd_518a_sbn_2.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_33/sim/bd_518a_s03mmu_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_34/sim/bd_518a_s03tr_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_35/sim/bd_518a_s03sic_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_28/sim/bd_518a_sarn_2.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_29/sim/bd_518a_srn_2.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_30/sim/bd_518a_sawn_1.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_31/sim/bd_518a_swn_1.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_32/sim/bd_518a_sbn_1.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_24/sim/bd_518a_s02mmu_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_25/sim/bd_518a_s02tr_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_26/sim/bd_518a_s02sic_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_22/sim/bd_518a_sarn_1.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_23/sim/bd_518a_srn_1.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_18/sim/bd_518a_s01mmu_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_19/sim/bd_518a_s01tr_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_20/sim/bd_518a_s01sic_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_13/sim/bd_518a_sarn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_14/sim/bd_518a_srn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_15/sim/bd_518a_sawn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_16/sim/bd_518a_swn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_17/sim/bd_518a_sbn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_9/sim/bd_518a_s00mmu_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_10/sim/bd_518a_s00tr_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_11/sim/bd_518a_s00sic_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/adb9" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/adb9" +incdir+"/home/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/4e7b/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/adb9" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/adb9" +incdir+"/home/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_4/sim/bd_518a_arsw_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_5/sim/bd_518a_rsw_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_6/sim/bd_518a_awsw_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_7/sim/bd_518a_wsw_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_8/sim/bd_518a_bsw_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/adb9" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/adb9" +incdir+"/home/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_0/sim/bd_518a_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_1/sim/bd_518a_psr0_0.vhd" \
    "$ref_dir/../../../bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_2/sim/bd_518a_psr_aclk_0.vhd" \
    "$ref_dir/../../../bd/system/ip/system_axi_mem_interconnect_0/bd_0/ip/ip_3/sim/bd_518a_psr_aclk1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/adb9" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/adb9" +incdir+"/home/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axi_mem_interconnect_0/sim/system_axi_mem_interconnect_0.v" \
    "$ref_dir/../../../bd/system/ip/system_GND_12_0/sim/system_GND_12_0.v" \
    "$ref_dir/../../../bd/system/ipshared/672f/axi_adxcvr_es.v" \
    "$ref_dir/../../../bd/system/ipshared/672f/axi_adxcvr_mdrp.v" \
    "$ref_dir/../../../bd/system/ipshared/672f/axi_adxcvr_mstatus.v" \
    "$ref_dir/../../../bd/system/ipshared/672f/axi_adxcvr_up.v" \
    "$ref_dir/../../../bd/system/ipshared/672f/axi_adxcvr.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ad9250_xcvr_0/sim/system_axi_ad9250_xcvr_0.v" \
    "$ref_dir/../../../bd/system/ipshared/b7fb/util_bsplit.v" \
    "$ref_dir/../../../bd/system/ip/system_data_bsplit_0/sim/system_data_bsplit_0.v" \
    "$ref_dir/../../../bd/system/common/ad_datafmt.v" \
    "$ref_dir/../../../bd/system/ipshared/6178/ad_ip_jesd204_tpl_adc_channel.v" \
    "$ref_dir/../../../bd/system/ipshared/6178/ad_ip_jesd204_tpl_adc_core.v" \
    "$ref_dir/../../../bd/system/ipshared/6178/ad_ip_jesd204_tpl_adc_deframer.v" \
    "$ref_dir/../../../bd/system/ipshared/6178/ad_ip_jesd204_tpl_adc_pnmon.v" \
    "$ref_dir/../../../bd/system/ipshared/6178/ad_ip_jesd204_tpl_adc_regmap.v" \
    "$ref_dir/../../../bd/system/common/ad_perfect_shuffle.v" \
    "$ref_dir/../../../bd/system/common/ad_pnmon.v" \
    "$ref_dir/../../../bd/system/common/ad_rst.v" \
    "$ref_dir/../../../bd/system/common/ad_xcvr_rx_if.v" \
    "$ref_dir/../../../bd/system/common/up_adc_channel.v" \
    "$ref_dir/../../../bd/system/common/up_adc_common.v" \
    "$ref_dir/../../../bd/system/common/up_clock_mon.v" \
    "$ref_dir/../../../bd/system/ipshared/ad_ip_jesd204_tpl_common/up_tpl_common.v" \
    "$ref_dir/../../../bd/system/common/up_xfer_cntrl.v" \
    "$ref_dir/../../../bd/system/common/up_xfer_status.v" \
    "$ref_dir/../../../bd/system/ipshared/6178/ad_ip_jesd204_tpl_adc.v" \
    "$ref_dir/../../../bd/system/ipshared/f5f0/axi_ad9250.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ad9250_0_core_0/sim/system_axi_ad9250_0_core_0.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ad9250_1_core_0/sim/system_axi_ad9250_1_core_0.v" \
    "$ref_dir/../../../bd/system/ipshared/util_pack_common/pack_ctrl.v" \
    "$ref_dir/../../../bd/system/ipshared/util_pack_common/pack_interconnect.v" \
    "$ref_dir/../../../bd/system/ipshared/util_pack_common/pack_network.v" \
    "$ref_dir/../../../bd/system/ipshared/util_pack_common/pack_shell.v" \
    "$ref_dir/../../../bd/system/ipshared/c14b/util_cpack2_impl.v" \
    "$ref_dir/../../../bd/system/ipshared/c14b/util_cpack2.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ad9250_0_cpack_0/sim/system_axi_ad9250_0_cpack_0.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ad9250_1_cpack_0/sim/system_axi_ad9250_1_cpack_0.v" \
    "$ref_dir/../../../bd/system/ipshared/cb53/sync_bits.v" \
    "$ref_dir/../../../bd/system/ipshared/cb53/sync_data.v" \
    "$ref_dir/../../../bd/system/ipshared/cb53/sync_event.v" \
    "$ref_dir/../../../bd/system/ipshared/cb53/sync_gray.v" \
    "$ref_dir/../../../bd/system/ipshared/common/ad_mem.v" \
    "$ref_dir/../../../bd/system/ipshared/cf62/address_gray_pipelined.v" \
    "$ref_dir/../../../bd/system/ipshared/cf62/address_sync.v" \
    "$ref_dir/../../../bd/system/ipshared/cf62/util_axis_fifo.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/adb9" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/adb9" +incdir+"/home/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axi_ad9250_0_dma_0/sim/system_axi_ad9250_0_dma_0_pkg.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/adb9" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/adb9" +incdir+"/home/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ipshared/adb9/2d_transfer.v" \
    "$ref_dir/../../../bd/system/ipshared/common/ad_mem_asym.v" \
    "$ref_dir/../../../bd/system/ipshared/adb9/address_generator.v" \
    "$ref_dir/../../../bd/system/ipshared/adb9/axi_dmac_burst_memory.v" \
    "$ref_dir/../../../bd/system/ipshared/adb9/axi_dmac_regmap.v" \
    "$ref_dir/../../../bd/system/ipshared/adb9/axi_dmac_regmap_request.v" \
    "$ref_dir/../../../bd/system/ipshared/adb9/axi_dmac_reset_manager.v" \
    "$ref_dir/../../../bd/system/ipshared/adb9/axi_dmac_resize_dest.v" \
    "$ref_dir/../../../bd/system/ipshared/adb9/axi_dmac_resize_src.v" \
    "$ref_dir/../../../bd/system/ipshared/adb9/axi_dmac_response_manager.v" \
    "$ref_dir/../../../bd/system/ipshared/adb9/axi_dmac_transfer.v" \
    "$ref_dir/../../../bd/system/ipshared/adb9/axi_register_slice.v" \
    "$ref_dir/../../../bd/system/ipshared/adb9/data_mover.v" \
    "$ref_dir/../../../bd/system/ipshared/adb9/dest_axi_mm.v" \
    "$ref_dir/../../../bd/system/ipshared/adb9/dest_axi_stream.v" \
    "$ref_dir/../../../bd/system/ipshared/adb9/dest_fifo_inf.v" \
    "$ref_dir/../../../bd/system/ipshared/adb9/request_arb.v" \
    "$ref_dir/../../../bd/system/ipshared/adb9/request_generator.v" \
    "$ref_dir/../../../bd/system/ipshared/adb9/response_generator.v" \
    "$ref_dir/../../../bd/system/ipshared/adb9/response_handler.v" \
    "$ref_dir/../../../bd/system/ipshared/adb9/splitter.v" \
    "$ref_dir/../../../bd/system/ipshared/adb9/src_axi_mm.v" \
    "$ref_dir/../../../bd/system/ipshared/adb9/src_axi_stream.v" \
    "$ref_dir/../../../bd/system/ipshared/adb9/src_fifo_inf.v" \
    "$ref_dir/../../../bd/system/ipshared/adb9/axi_dmac.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ad9250_0_dma_0/sim/system_axi_ad9250_0_dma_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/adb9" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/adb9" +incdir+"/home/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axi_ad9250_1_dma_0/sim/system_axi_ad9250_1_dma_0_pkg.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/adb9" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/adb9" +incdir+"/home/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axi_ad9250_1_dma_0/sim/system_axi_ad9250_1_dma_0.v" \
    "$ref_dir/../../../bd/system/ipshared/0b7c/util_adxcvr_xch.v" \
    "$ref_dir/../../../bd/system/ipshared/0b7c/util_adxcvr_xcm.v" \
    "$ref_dir/../../../bd/system/ipshared/0b7c/util_adxcvr.v" \
    "$ref_dir/../../../bd/system/ip/system_util_fmcjesdadc1_xcvr_0/sim/system_util_fmcjesdadc1_xcvr_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_ad9250_jesd_rstgen_0/sim/system_axi_ad9250_jesd_rstgen_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/adb9" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/adb9" +incdir+"/home/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ipshared/04c7/jesd204_up_common.v" \
    "$ref_dir/../../../bd/system/ipshared/04c7/jesd204_up_sysref.v" \
    "$ref_dir/../../../bd/system/ipshared/7aaf/jesd204_up_ilas_mem.v" \
    "$ref_dir/../../../bd/system/ipshared/7aaf/jesd204_up_rx.v" \
    "$ref_dir/../../../bd/system/ipshared/7aaf/jesd204_up_rx_lane.v" \
    "$ref_dir/../../../bd/system/ipshared/7aaf/axi_jesd204_rx.v" \
    "$ref_dir/../../../bd/system/ip/system_rx_axi_0/sim/system_rx_axi_0.v" \
    "$ref_dir/../../../bd/system/ipshared/7dd4/jesd204_eof_generator.v" \
    "$ref_dir/../../../bd/system/ipshared/7dd4/jesd204_lmfc.v" \
    "$ref_dir/../../../bd/system/ipshared/7dd4/jesd204_scrambler.v" \
    "$ref_dir/../../../bd/system/ipshared/7dd4/pipeline_stage.v" \
    "$ref_dir/../../../bd/system/ipshared/fb83/align_mux.v" \
    "$ref_dir/../../../bd/system/ipshared/fb83/elastic_buffer.v" \
    "$ref_dir/../../../bd/system/ipshared/fb83/jesd204_ilas_monitor.v" \
    "$ref_dir/../../../bd/system/ipshared/fb83/jesd204_lane_latency_monitor.v" \
    "$ref_dir/../../../bd/system/ipshared/fb83/jesd204_rx_cgs.v" \
    "$ref_dir/../../../bd/system/ipshared/fb83/jesd204_rx_ctrl.v" \
    "$ref_dir/../../../bd/system/ipshared/fb83/jesd204_rx_lane.v" \
    "$ref_dir/../../../bd/system/ipshared/fb83/jesd204_rx.v" \
    "$ref_dir/../../../bd/system/ip/system_rx_0/sim/system_rx_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/adb9" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/adb9" +incdir+"/home/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/adb9" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/adb9" +incdir+"/home/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_17 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/adb9" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/adb9" +incdir+"/home/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/6020/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_16 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/adb9" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/adb9" +incdir+"/home/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/247d/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_18 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/adb9" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/adb9" +incdir+"/home/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/15a3/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/adb9" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/adb9" +incdir+"/home/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_xbar_0/sim/system_xbar_0.v" \
    "$ref_dir/../../../bd/system/sim/system.v" \
    "$ref_dir/../../../bd/system/ip/system_tier2_xbar_0_0/sim/system_tier2_xbar_0_0.v" \
    "$ref_dir/../../../bd/system/ip/system_tier2_xbar_1_0/sim/system_tier2_xbar_1_0.v" \
    "$ref_dir/../../../bd/system/ip/system_tier2_xbar_2_0/sim/system_tier2_xbar_2_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_17 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/adb9" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/adb9" +incdir+"/home/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/ccfb/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/adb9" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../fmcjesdadc1_kc705.srcs/sources_1/bd/system/ipshared/adb9" +incdir+"/home/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_auto_pc_0/sim/system_auto_pc_0.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.system xil_defaultlib.glbl -o system_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./system_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./system.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  else
    lib_map_path="/home/bernardo/FPGA/ESTHER_TRIGGER/hdl/projects/fmcjesdadc1/kc705/fmcjesdadc1_kc705.cache/compile_simlib/vcs"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key system_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc system_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./system.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: system.sh [-help]\n\
Usage: system.sh [-lib_map_path]\n\
Usage: system.sh [-reset_run]\n\
Usage: system.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
