# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config  -ruleid {1}  -id {Vivado 12-1790}  -string {{Evaluation} {features} {should} {NOT} {be} {used} {in} {production} {systems.}}  -new_severity {WARNING} 
set_msg_config  -ruleid {10}  -id {Place 30-73}  -string {{axi_spi}}  -new_severity {WARNING} 
set_msg_config  -ruleid {11}  -string {{PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY}}  -new_severity {WARNING} 
set_msg_config  -ruleid {2}  -id {BD 41-1343}  -new_severity {WARNING} 
set_msg_config  -ruleid {3}  -id {BD 41-1306}  -new_severity {WARNING} 
set_msg_config  -ruleid {4}  -id {BD 41-1276}  -severity {CRITICAL WARNING}  -new_severity {ERROR} 
set_msg_config  -ruleid {5}  -id {IP_Flow 19-3656}  -new_severity {INFO} 
set_msg_config  -ruleid {6}  -id {IP_Flow 19-4623}  -new_severity {INFO} 
set_msg_config  -ruleid {7}  -id {IP_Flow 19-459}  -new_severity {INFO} 
set_msg_config  -ruleid {8}  -id {Synth 8-3331}  -new_severity {INFO} 
set_msg_config  -ruleid {9}  -id {Designutils 20-3303}  -string {{HDPYFinalizeIO}}  -new_severity {INFO} 
set_param project.vivado.isBlockSynthRun true
set_msg_config -msgmgr_mode ooc_run
create_project -in_memory -part xc7k325tffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/francisco/kc705_changes/fmcjesdadc1_kc705.cache/wt [current_project]
set_property parent.project_path /home/francisco/kc705_changes/fmcjesdadc1_kc705.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:kc705:part0:1.1 [current_project]
set_property ip_repo_paths /home/bernardo/FPGA/ESTHER_TRIGGER/hdl/library [current_project]
set_property ip_output_repo /home/francisco/kc705_changes/fmcjesdadc1_kc705.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_ip -quiet /home/francisco/kc705_changes/esther-trigger-hdl/src/ip/pcie_7x_0.xci
set_property used_in_implementation false [get_files -all /home/francisco/kc705_changes/esther-trigger-hdl/src/ip/source/pcie_7x_0-PCIE_X0Y0.xdc]
set_property used_in_implementation false [get_files -all /home/francisco/kc705_changes/esther-trigger-hdl/src/ip/synth/pcie_7x_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0

set cached_ip [config_ip_cache -export -no_bom -use_project_ipc -dir /home/francisco/kc705_changes/fmcjesdadc1_kc705.runs/pcie_7x_0_synth_1 -new_name pcie_7x_0 -ip [get_ips pcie_7x_0]]

if { $cached_ip eq {} } {
close [open __synthesis_is_running__ w]

synth_design -top pcie_7x_0 -part xc7k325tffg900-2 -mode out_of_context

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
# disable binary constraint mode for IPCache checkpoints
set_param constraints.enableBinaryConstraints false

catch {
 write_checkpoint -force -noxdef -rename_prefix pcie_7x_0_ pcie_7x_0.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ pcie_7x_0_stub.v
 lappend ipCachedFiles pcie_7x_0_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ pcie_7x_0_stub.vhdl
 lappend ipCachedFiles pcie_7x_0_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ pcie_7x_0_sim_netlist.v
 lappend ipCachedFiles pcie_7x_0_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ pcie_7x_0_sim_netlist.vhdl
 lappend ipCachedFiles pcie_7x_0_sim_netlist.vhdl
set TIME_taken [expr [clock seconds] - $TIME_start]

 config_ip_cache -add -dcp pcie_7x_0.dcp -move_files $ipCachedFiles -use_project_ipc  -synth_runtime $TIME_taken  -ip [get_ips pcie_7x_0]
}

rename_ref -prefix_all pcie_7x_0_

# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef pcie_7x_0.dcp
create_report "pcie_7x_0_synth_1_synth_report_utilization_0" "report_utilization -file pcie_7x_0_utilization_synth.rpt -pb pcie_7x_0_utilization_synth.pb"

if { [catch {
  file copy -force /home/francisco/kc705_changes/fmcjesdadc1_kc705.runs/pcie_7x_0_synth_1/pcie_7x_0.dcp /home/francisco/kc705_changes/esther-trigger-hdl/src/ip/pcie_7x_0.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub /home/francisco/kc705_changes/esther-trigger-hdl/src/ip/pcie_7x_0_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub /home/francisco/kc705_changes/esther-trigger-hdl/src/ip/pcie_7x_0_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim /home/francisco/kc705_changes/esther-trigger-hdl/src/ip/pcie_7x_0_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim /home/francisco/kc705_changes/esther-trigger-hdl/src/ip/pcie_7x_0_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


if { [catch {
  file copy -force /home/francisco/kc705_changes/fmcjesdadc1_kc705.runs/pcie_7x_0_synth_1/pcie_7x_0.dcp /home/francisco/kc705_changes/esther-trigger-hdl/src/ip/pcie_7x_0.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  file rename -force /home/francisco/kc705_changes/fmcjesdadc1_kc705.runs/pcie_7x_0_synth_1/pcie_7x_0_stub.v /home/francisco/kc705_changes/esther-trigger-hdl/src/ip/pcie_7x_0_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force /home/francisco/kc705_changes/fmcjesdadc1_kc705.runs/pcie_7x_0_synth_1/pcie_7x_0_stub.vhdl /home/francisco/kc705_changes/esther-trigger-hdl/src/ip/pcie_7x_0_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force /home/francisco/kc705_changes/fmcjesdadc1_kc705.runs/pcie_7x_0_synth_1/pcie_7x_0_sim_netlist.v /home/francisco/kc705_changes/esther-trigger-hdl/src/ip/pcie_7x_0_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  file rename -force /home/francisco/kc705_changes/fmcjesdadc1_kc705.runs/pcie_7x_0_synth_1/pcie_7x_0_sim_netlist.vhdl /home/francisco/kc705_changes/esther-trigger-hdl/src/ip/pcie_7x_0_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

}; # end if cached_ip 

if {[file isdir /home/francisco/kc705_changes/fmcjesdadc1_kc705.ip_user_files/ip/pcie_7x_0]} {
  catch { 
    file copy -force /home/francisco/kc705_changes/esther-trigger-hdl/src/ip/pcie_7x_0_stub.v /home/francisco/kc705_changes/fmcjesdadc1_kc705.ip_user_files/ip/pcie_7x_0
  }
}

if {[file isdir /home/francisco/kc705_changes/fmcjesdadc1_kc705.ip_user_files/ip/pcie_7x_0]} {
  catch { 
    file copy -force /home/francisco/kc705_changes/esther-trigger-hdl/src/ip/pcie_7x_0_stub.vhdl /home/francisco/kc705_changes/fmcjesdadc1_kc705.ip_user_files/ip/pcie_7x_0
  }
}
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
